require('plugins')
require('settings')
require('keybinds')
require ('user.treesitter')
require ('user.lsp')
require('user.telescope-config')
require('user.bufferline')
require('user.lualine')
require('user.neoscroll')
require('user.completion')
require('user.autopairs')
