require("neotest").setup({
	adapters = {
		require("neotest-python")({
			dap = { justMyCode = false },
			args = { "-v" },
			runner = "pytest",
		}),
		require("neotest-rust"),
	},
	icons = {
		expanded = "",
		child_prefix = "",
		child_indent = "",
		final_child_prefix = "",
		non_collapsible = "",
		collapsed = "",
		passed = "",
		running = "",
		failed = "",
		unknown = "",
		--[[ child_indent = "│",
      child_prefix = "├",
      collapsed = "─",
      expanded = "╮",
      failed = "✖",
      final_child_indent = " ",
      final_child_prefix = "╰",
      non_collapsible = "─",
      passed = "✔",
      running = "🗘",
      running_animated = { "/", "|", "\\", "-", "/", "|", "\\", "-" },
      skipped = "ﰸ",
      unknown = "?" ]]
	},
})
